### Send auth request
POST {{keycloak_host}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&username={{username}}&password={{password}}&grant_type=password

> {% client.global.set("auth_token", response.body.access_token); %}

### Get list surveys
GET {{survey_host}}/api/admin/survey/all?onlyFavorites=false&isDeleted=false
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


### Get survey
GET {{survey_host}}/api/admin/survey?id={{survey_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
