### Send auth request
POST {{keycloak_host}}/auth/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&username={{username}}&password={{password}}&grant_type=password

> {% client.global.set("auth_token", response.body.access_token); %}

### Start passing
POST {{survey_host}}/api/passing/survey
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "surveyId": "{{survey_id}}",
  "timezone": "GMT+05:00"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.global.set("survey_passing_id", response.body.surveyPassingId);
%}

### Answer the choice question
POST {{survey_host}}/api/passing/survey/answer
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "surveyPassingId": "{{survey_passing_id}}",
  "type": "CHOICE_ANSWER",
  "answerIds": ["{{choice_question_answer_option_1}}", "{{choice_question_answer_option_2}}"]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Get previous question
GET {{survey_host}}/api/passing/survey/answer/previous?surveyPassingId={{survey_passing_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Reanswer the choice question
POST {{survey_host}}/api/passing/survey/answer
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "surveyPassingId": "{{survey_passing_id}}",
  "type": "DIFFICULT_TO_ANSWER"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Answer the scale question
POST {{survey_host}}/api/passing/survey/answer
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "surveyPassingId": "{{survey_passing_id}}",
  "type": "SCALE_ANSWER",
  "scaleValue": 2,
  "comment": "Comment"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Answer the open question
POST {{survey_host}}/api/passing/survey/answer
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "surveyPassingId": "{{survey_passing_id}}",
  "type": "OPEN_ANSWER",
  "answer": "Answer"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
