version: '3'

volumes:
  minio-storage: null

services:
  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: s3_access_key
      MINIO_SECRET_KEY: s3_secret_key
      MINIO_OPTS: "--config-dir /root/.minio --console-address :9001 --address :9000 --anonymous"
    volumes:
      - minio-storage:/data
      - ./minio/cors.xml:/root/.minio/cors.xml
